services:

  #api development build
  payload:
    build:
      target: payload
    container_name: payload.dev
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - db
    restart: unless-stopped
    #enabling hot reload by binding the project folder
    volumes:
      - type: bind
        source: ./
        target: /home/node/workspace


  #db development build
  db:
    build:
      target: db
    container_name: db.dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: data
        target: /data/db

  #db-pg development build
  db-pg:
    build:
      target: db-pg
    container_name: db-pg.dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-pg
        target: /var/lib/postgresql/data

networks:
  default:
    name: workspace-dev

volumes:
  data:
    name: workspace-vol-data
  data-pg:
    name: workspace-vol-data-pg