services:

  #api development build
  payload:
    build:
      target: payload
    container_name: payload.dev
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - db
    restart: unless-stopped
    #enabling hot reload by binding the project folder
    volumes:
      - type: bind
        source: ./
        target: /home/node/workspace


  #db as MongoDB replica set development build
  db:
    build:
      target: db
    container_name: db.dev
    command:
      - --config
      - /etc/mongodb/config.yaml
    healthcheck:
      test: mongosh -u root -p secret --quiet --file /etc/mongodb/init.js
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    restart: unless-stopped
    volumes:
      - type: volume
        source: db-data
        target: /data/db
      - type: volume
        source: db-config
        target: /data/configdb

  #db as Postgres development build
  db-pg:
    build:
      target: db-pg
    container_name: db-pg.dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-pg
        target: /var/lib/postgresql/data

networks:
  default:
    name: workspace-dev

volumes:
  db-data:
    name: workspace-vol-db-data
  db-config:
    name: workspace-vol-db-config
  data-pg:
    name: workspace-vol-data-pg